// eduHub-Frontend/src/pages/Payment1.jsx
import React from 'react'
import { useNavigate } from 'react-router-dom'

export default function Payment1() {
  const navigate = useNavigate()

  function redirectToPayments() {
    navigate('/payment2')
  }

  const plans = [
    {
      id: 'basic',
      name: 'Basic Plan Member',
      price: '$25.0 / month Billed annually',
      label: 'Select Basic',
      discount: '-10%',
      save: 'save 10 $',
      features: 'Access to Sample Courses · Basic Study Tools · Community Access (Limited) · Weekly Progress Summary · Support Access',
      color: '#4a90d9',
    },
    {
      id: 'standard',
      name: 'Standard Plan Member',
      price: '$40.0 / month Billed annually',
      label: 'Select Standard',
      discount: '-15%',
      save: 'save 20 $',
      features: 'All Basic features · 30% discount on Uni Courses · 30% discount for products · Full Access to Course Library · Self-Assessment · Community Access (Limited) · Support Access',
      color: '#5cb85c',
    },
    {
      id: 'premium',
      name: 'Premium Plan Member',
      price: '$50.0 / month Billed annually',
      label: 'Select Premium',
      discount: '-25%',
      save: 'save 35 $',
      features: 'All Basic features · 45% discount on Uni Courses · 45% discount for products · Full Access to Core Course · Personal assistance · Advanced Study Tools · Interactive Quizzes · Personalized Feedback',
      color: '#d9534f',
    },
  ]

  return (
    <div
      style={{
        minHeight: '100vh',
        padding: '40px 20px',
        background: 'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
      }}
    >
      <h1 style={{ fontSize: '2.5rem', fontWeight: 700, color: '#333', marginBottom: '8px', textAlign: 'center' }}>
        Choose the best plan for you.
      </h1>
      <p style={{ color: '#666', marginBottom: '40px', textAlign: 'center' }}>
        Unlock unlimited learning with a plan that fits your goals.
      </p>

      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
          gap: '30px',
          maxWidth: '1000px',
          width: '100%',
        }}
      >
        {plans.map(plan => (
          <div
            key={plan.id}
            style={{
              backgroundColor: '#fff',
              borderRadius: '16px',
              boxShadow: '0 8px 30px rgba(0,0,0,0.1)',
              padding: '30px',
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              textAlign: 'center',
              position: 'relative',
              transition: 'transform 0.3s ease',
            }}
            onMouseEnter={e => e.currentTarget.style.transform = 'translateY(-8px)'}
            onMouseLeave={e => e.currentTarget.style.transform = 'translateY(0)'}
          >
            <div
              style={{
                position: 'absolute',
                top: '-12px',
                right: '20px',
                backgroundColor: '#ff6b6b',
                color: '#fff',
                borderRadius: '12px',
                padding: '4px 14px',
                fontSize: '0.85rem',
                fontWeight: 700,
              }}
            >
              {plan.discount}
            </div>

            <h2 style={{ fontSize: '1.3rem', fontWeight: 700, color: '#333', marginBottom: '10px' }}>
              {plan.name}
            </h2>
            <p style={{ fontSize: '1rem', color: '#666', marginBottom: '5px' }}>{plan.price}</p>

            <div
              style={{
                backgroundColor: '#e8f5e9',
                color: '#2e7d32',
                borderRadius: '8px',
                padding: '4px 14px',
                fontSize: '0.85rem',
                fontWeight: 600,
                marginBottom: '20px',
              }}
            >
              {plan.save}
            </div>

            <button
              onClick={redirectToPayments}
              style={{
                backgroundColor: plan.color,
                color: '#fff',
                border: 'none',
                borderRadius: '25px',
                padding: '12px 30px',
                fontSize: '1rem',
                fontWeight: 600,
                cursor: 'pointer',
                marginBottom: '20px',
                width: '100%',
                transition: 'opacity 0.2s',
              }}
              onMouseEnter={e => e.currentTarget.style.opacity = '0.85'}
              onMouseLeave={e => e.currentTarget.style.opacity = '1'}
            >
              {plan.label}
            </button>

            <p style={{ fontSize: '0.9rem', color: '#555', lineHeight: 1.8 }}>
              {plan.features.split(' · ').map((f, i) => (
                <span key={i}>
                  <i className="fas fa-check text-success me-1" style={{ fontSize: '0.8rem' }}></i>
                  {f}<br />
                </span>
              ))}
            </p>
          </div>
        ))}
      </div>
    </div>
  )
}

// eduHub-Frontend/src/app/pages/payment1/payment1.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-payment1',
  standalone: true,
  imports: [],
  templateUrl: './payment1.component.html',
  styleUrls: ['./payment1.component.css']
})
export class Payment1Component {
  constructor(private router: Router) {}

  // Define the redirectToPayments method
  redirectToPayments(): void {
    // Navigate to the payment page
    this.router.navigate(['/payment2']); // Replace '/payment2' with your target route
  }
}
<div class="sub_564-721">
  <div class="group-30_564-730">
    <span class="text-choose-the-best-plan-for-you-_564-731">
      Choose the best plan for you.
    </span>
  </div>

  <div class="frame-72_564-733">
    <span class="text-basic-plan-member_564-735">Basic Plan Member</span>
    <span class="text-25-0---month-billed-annually-you_564-736">
      $25.0 / month Billed annually you
    </span>
    <div class="frame-95_564-737">
      <button (click)="redirectToPayments()" class="text-select-basic_564-738">
        Select Basic
      </button>
    </div>
    <span
      class="text-access-to-sample-courses-basic-study-tools-community-access--limited--weekly-progress-summary-support-access_564-739">
      Access to Sample Courses Basic Study Tools Community Access (Limited)
      Weekly Progress Summary Support Access
    </span>
    <div class="frame-94_564-740">
      <span class="text---10-_564-741"> -10%</span>
    </div>
    <div class="frame-93_564-742">
      <span class="text-save-10--_564-743">save 10 $</span>
    </div>
  </div>

  <div class="frame-95_564-744">
    <span class="text-standard-plan-member_564-746">Standard Plan Member</span>
    <span class="text-40-0---month-billed-annually-you_564-747">
      $40.0 / month Billed annually you
    </span>
    <div class="frame-95_564-748">
      <button (click)="redirectToPayments()" class="text-select-standard_564-749">
        Select Standard
      </button>
    </div>
    <span
      class="text-all-basic-features-30--discount-on-uni-courses-30--discount-for-products-full-access-to-course-library-self-assessment-community-access--limited--support-access_564-750">
      All Basic features 30% discount on Uni Courses 30% discount for products
      Full Access to Course Library Self-Assessment Community Access (Limited)
      Support Access
    </span>
    <div class="frame-94_564-751">
      <span class="text---15-_564-752"> -15%</span>
    </div>
    <div class="frame-93_564-753">
      <span class="text-save-20--_564-754">save 20 $</span>
    </div>
  </div>

  <div class="frame-74_564-755">
    <span class="text-premium-plan-member_564-757">Premium Plan Member</span>
    <span class="text-50-0---month-billed-annually-you_564-758">
      $50.0 / month Billed annually you
    </span>
    <div class="frame-95_564-759">
      <button (click)="redirectToPayments()" class="text-select-premium_564-760">
        Select Premium
      </button>
    </div>
    <span
      class="text-all-basic-features-45--discount-on-uni-courses-45--discount-for-products-full-access-to-core-course-personal-assistance-advanced-study-tools-interactive-quizzes-personalized-feedback_564-761">
      All Basic features 45% discount on Uni Courses 45% discount for products
      Full Access to Core Course Personal assistance Advanced Study Tools
      Interactive Quizzes Personalized Feedback
    </span>
    <div class="frame-94_564-762">
      <span class="text---25-_564-763"> -25%</span>
    </div>
    <div class="frame-93_564-764">
      <span class="text-save-35--_564-765">save 35 $</span>
    </div>
  </div>
